version: '2'

services:
    backend:
        cpu_quota: 400000
        mem_limit: 512mb
        build: 
            context: .
            dockerfile: dockerfile-nodejs
#       build: .
        ports:
            - 8080

    app:
        build: ./haproxy
        expose: 
            - 8080
        ports:
            - 8080
        links:
            - consul
        restart: always

#    pub:
#        build:
#            context: .
#            dockerfile: Dockerfile-publish
#        volumes:
#            - .:/code
#        links:
#            - pushpin

    consul:
        image:  gliderlabs/consul-server:latest
        command: "-advertise=${MYHOST} -server -bootstrap"
        container_name: consul
        hostname: ${MYHOST}
        ports:
            - 8500:8500

    registrator:
        image: gliderlabs/registrator:latest
        command: "-ip ${MYHOST} consul://${MYHOST}:8500"
        container_name: registrator
        hostname: ${MYHOST}
        depends_on:
            - consul
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock

    pushpin:
        cpu_quota: 1000000
        mem_limit: 8g
        environment:
            - LOGNAME=nobody
        image: fanout/pushpin
#        build: 
#            context: .
#            dockerfile: Dockerfile-pushpin
        links:
            - app
        ports:
            - "7999"
            - "5562"
            - "5561"
            - "5563"
            - "5560"
