version: '2'

services:
    app:
        build: .
        volumes:
            - .:/code
        ports:
            - 5000:8080

    pub:
        build:
            context: .
            dockerfile: Dockerfile-publish
        volumes:
            - .:/code
        links:
            - pushpin

    consul:
        image:  gliderlabs/consul-server:latest
        command: "-advertise=${MYHOST} -server -bootstrap"
        container_name: consul
        hostname: ${MYHOST}
        ports:
            - 8500:8500

    registrator:
        image: gliderlabs/registrator:latest
        command: "-ip ${MYHOST} consul://${MYHOST}:8500"
        container_name: registrator
        hostname: ${MYHOST}
        depends_on:
            - consul
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock

    pushpin:
        cpu_quota: 150000
        mem_limit: 1024m
        environment:
            - LOGNAME=nobody
        image: fanout/pushpin
#        build: 
#            context: .
#            dockerfile: Dockerfile-pushpin
        links:
            - app
        ports:
            - "7999"
            - "5562"
            - "5561"
            - "5563"
            - "5560"
